version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-node-browsers
      - image: circleci/mysql:5.7
        command: [--max_allowed_packet=32M]

test:
    working_directory: ~/circleci-php
    docker:
      - image: "circleci/php:7.2-apache-node-browsers"
    steps:
      - checkout
      - run: php sp_insertar.php

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build